import type { LiftModel, ModelNode } from './documents-model.js';
import type { SkeletonServer, SkeletonService } from './skeleton.js';

/**
 * civil/architecture.md: the overview a lift writes beside the canvas — what was
 * found, where each node's code lives, what the canvas leaves out (infrastructure),
 * every route each boundary serves, and what the reader could not resolve. The canvas
 * is the shape; this is the inventory a reviewer checks the shape against.
 *
 * Deterministic like every lifted document: built only from the model and the ids the
 * documents ended up using, sorted, no dates — so an Update with nothing new in the
 * repository rewrites it byte for byte.
 */

export interface ArchitectureInput {
  projectName: string;
  model: LiftModel;
  /** Lift id → the id the composition uses (the author's, after an Update). */
  ids: ReadonlyMap<string, string>;
  /** Lift service id → the graph document its agents are drawn in. */
  graphPaths: ReadonlyMap<string, string>;
  /** Lift service id → (lift graph node id → the id its graph uses). */
  graphNodeIds: ReadonlyMap<string, ReadonlyMap<string, string>>;
}

const code = (text: string): string => `\`${text.replace(/`/g, "'")}\``;
const cell = (text: string): string => text.replace(/\|/g, '\\|');
const plural = (n: number, one: string, many = `${one}s`): string => `${n} ${n === 1 ? one : many}`;

function fileList(files: readonly string[]): string {
  return files.length ? files.map(code).join(', ') : '—';
}

export function architectureMarkdown(input: ArchitectureInput): string {
  const { model, ids } = input;
  const { skeleton } = model;
  const idOf = (liftId: string) => ids.get(liftId) ?? liftId;
  const of = (type: ModelNode['type']) => model.nodes.filter((n) => n.type === type);
  const clients = of('client');
  const boundaries = of('boundary');
  const services = of('service');
  const processes = of('process');
  const graphs = services.filter((s) => s.graph);
  const routes = skeleton.servers.reduce((n, s) => n + s.routes.length, 0);

  const out: string[] = [
    `# ${input.projectName} — architecture`,
    '',
    "> Generated by Civil's **Generate graph from repo** from the repository's code, and",
    '> rebuilt on every **Update graph from repo**. Notes of your own belong in CIVIL.md.',
    '',
    '## Overview',
    '',
  ];

  if (model.summary) out.push(model.summary, '');
  else {
    const frameworks = skeleton.frameworks.length ? ` (${skeleton.frameworks.join(', ')})` : '';
    const packages = new Set(skeleton.servers.map((s) => s.path)).size;
    const deployed =
      packages === boundaries.length
        ? ''
        : ` The backend is deployed as ${plural(boundaries.length, 'service')}, one per root module its bootstrap can start.`;
    out.push(
      `The repository has ${plural(clients.length, 'frontend app')} and ${plural(packages, 'backend app')}${frameworks}.${deployed} ` +
        `The canvas shows each frontend as a client, each backend as an api boundary over the services that serve its routes, ` +
        `and scheduled work as processes; cross-cutting modules are listed under Infrastructure rather than drawn.`,
      '',
    );
  }

  out.push(
    '## What was found',
    '',
    '| | Count |',
    '|---|---|',
    `| Clients (frontend apps) | ${clients.length} |`,
    `| Api boundaries (backend apps) | ${boundaries.length} |`,
    `| Services on the canvas | ${services.length}${graphs.length ? ` (${graphs.length} with an agent graph)` : ''} |`,
    `| Infrastructure modules (off the canvas) | ${model.infrastructure.length} |`,
    `| Agents | ${skeleton.agents.length} |`,
    `| Routes | ${routes} |`,
    `| Scheduled processes | ${processes.length} |`,
    `| Unresolved | ${skeleton.unresolved.length} |`,
    '',
  );

  const describe = (n: ModelNode) => (n.description ? ` ${n.description}` : '');

  out.push('## The canvas', '');
  if (clients.length) {
    out.push('### Clients', '');
    for (const n of clients) {
      const dev = typeof n.node['dev'] === 'string' ? ` Dev: ${code(n.node['dev'] as string)}.` : '';
      out.push(`- **${idOf(n.id)}** — ${code(n.label)}.${describe(n)}${dev} Files: ${fileList(n.files)}.`);
    }
    out.push('');
  }
  if (boundaries.length) {
    out.push('### Boundaries', '');
    for (const n of boundaries) {
      const server = skeleton.servers.find((s) => input.model.boundaryOf[s.id] === n.id);
      const prefix = server?.globalPrefix ? `, global prefix ${code(server.globalPrefix)}` : '';
      const exposes = (n.node['exposes'] as string[]).map(idOf);
      const groups = server ? routeGroups(server) : '';
      const root = server?.rootModule
        ? ` One of the deployments the bootstrap chooses between: it boots ${code(server.rootModule)}.`
        : '';
      const internal = server?.internal
        ? ' Internal: nothing it serves is under the global prefix and no client calls it; ' +
          'it is started by the scheduled processes below and by the services that dispatch work to it.'
        : '';
      out.push(
        `- **${idOf(n.id)}** — api over the backend in ${code(n.label)}${prefix}.${describe(n)}${root}${internal} ` +
          `${groups}Exposes: ${exposes.length ? exposes.join(', ') : 'nothing on the canvas'}. Files: ${fileList(n.files)}.`,
      );
    }
    out.push('');
  }
  if (services.length) {
    out.push('### Services', '');
    for (const n of services) {
      const impl = n.node['impl'] as { entrypoint?: string };
      const how = n.graph
        ? `a graph, ${code(input.graphPaths.get(n.id) ?? '')}, with ${n.graph.nodes.filter((g) => g.type === 'agent').map((g) => input.graphNodeIds.get(n.id)?.get(g.id) ?? g.id).join(', ') || 'no agents found'}`
        : `entrypoint ${code(impl.entrypoint ?? '')}`;
      const deps = model.edges.filter((e) => e.kind === 'depends-on' && e.from === n.id).map((e) => idOf(e.to));
      const lifted = skeleton.services.find((x) => x.id === n.id);
      const dispatch = lifted?.dispatchesTo?.length
        ? ` Starts work on ${lifted.dispatchesTo.map(idOf).join(', ')} by naming its internal routes (a queued task or a call to that deployment).`
        : '';
      out.push(
        `- **${idOf(n.id)}** — ${code(n.label)}.${describe(n)} Implemented as ${how}.` +
          `${deps.length ? ` Depends on ${deps.join(', ')}.` : ''}${dispatch} Files: ${fileList(n.files)}.`,
      );
    }
    out.push('');
  }
  if (processes.length) {
    out.push('### Processes', '');
    for (const n of processes) {
      const trigger = n.node['trigger'] as { cron: string };
      const calls = (n.node['calls'] as string[]).map(idOf);
      const lifted = skeleton.processes.find((p) => p.id === n.id);
      const external = lifted?.route ? ` A scheduler job in the infrastructure code posts ${code(lifted.route)}.` : '';
      out.push(
        `- **${idOf(n.id)}** — on schedule ${code(trigger.cron)}.${external}${describe(n)}` +
          `${calls.length ? ` Calls ${calls.join(', ')}.` : ''} Files: ${fileList(n.files)}.`,
      );
    }
    out.push('');
  }
  if (skeleton.agents.length) {
    out.push('### Agents', '');
    for (const agent of [...skeleton.agents].sort((a, b) => (a.id < b.id ? -1 : 1))) {
      const users = services.filter((s) => s.graph?.nodes.some((g) => g.type === 'agent' && g.anchors.includes(agent.source.file)));
      const tools = agent.tools.map((t) => code(t.name)).join(', ');
      const description = model.descriptions[agent.id] ? ` ${model.descriptions[agent.id]}` : '';
      const callers = sortedIds(skeleton.services.flatMap((s) => s.agentsVia?.[agent.id] ?? []));
      const via = callers.length ? `, called by ${callers.join(', ')}` : '';
      out.push(
        `- **${agent.id}** — used by ${users.length ? users.map((s) => idOf(s.id)).join(', ') : 'no service on the canvas'}${via}.${description}` +
          `${tools ? ` Tools: ${tools}.` : ''} Files: ${fileList([...agent.files].sort())}.`,
      );
    }
    out.push('');
  }

  // Which canvas node (or infrastructure module) serves a route, by its controller.
  // On a server read as several deployments, the module that serves a route there:
  // a health check both roots declare is served by each, and said under each.
  const servedBy = (server: SkeletonServer, controller: string, file: string): string => {
    const declares = (s: SkeletonService) => s.controllers.some((c) => c.name === controller && c.file === file);
    const service =
      skeleton.services.find((s) => s.server === server.id && declares(s)) ??
      skeleton.services.find((s) => declares(s)) ??
      skeleton.services.find((s) => s.controllers.some((c) => c.name === controller));
    if (!service) return '—';
    if (service.root && service.infrastructure) return `${idOf(model.boundaryOf[server.id] ?? server.id)} (root module ${service.moduleClass})`;
    return service.infrastructure ? `${service.id} (infrastructure)` : idOf(service.id);
  };

  if (routes > 0) {
    out.push('## Routes', '');
    for (const server of [...skeleton.servers].sort((a, b) => (a.id < b.id ? -1 : 1))) {
      if (!server.routes.length) continue;
      out.push(`### ${idOf(model.boundaryOf[server.id] ?? server.id)}`, '', '| Method | Path | Handler | Service |', '|---|---|---|---|');
      const sorted = [...server.routes].sort((a, b) =>
        a.path === b.path ? (a.method < b.method ? -1 : a.method > b.method ? 1 : 0) : a.path < b.path ? -1 : 1,
      );
      for (const r of sorted) {
        const where = `${r.source.file}${r.source.line ? `:${r.source.line}` : ''}`;
        out.push(`| ${r.method} | ${cell(code(r.path))} | ${cell(`${r.controller}.${r.handler}`)} (${cell(code(where))}) | ${cell(servedBy(server, r.controller, r.source.file))} |`);
      }
      out.push('');
    }
  }

  if (model.infrastructure.length) {
    out.push(
      '## Infrastructure',
      '',
      'Cross-cutting modules every service leans on. They are recorded under `shared` in',
      'civil/registry.yaml and left off the canvas so it shows what the product does.',
      '',
    );
    for (const s of model.infrastructure) {
      const description = model.descriptions[s.id] ? ` ${model.descriptions[s.id]}` : '';
      const root = s.root
        ? ` The root module of ${idOf(model.boundaryOf[s.server] ?? s.server)}: the boundary stands for it on the canvas; what it declares itself is plumbing.`
        : '';
      out.push(`- **${s.id}** — ${code(s.moduleClass)}.${root}${description} Files: ${fileList(infraFiles(s))}.`);
    }
    out.push('');
  }

  const shared = sortedIds(skeleton.servers.flatMap((s) => s.sharedFiles ?? []));
  if (shared.length) {
    out.push(
      '## Shared code',
      '',
      `${plural(shared.length, 'file')} of server code belong to no module or agent — the bootstrap, connectors,`,
      'helpers several modules import. They are recorded under `shared` in civil/registry.yaml; the canvas',
      'draws them nowhere.',
      '',
      ...sharedSummary(shared),
      '',
    );
  }

  if (skeleton.unresolved.length || model.notes.length) {
    out.push('## Unresolved', '', 'What the reader saw but could not resolve, and what the mapping had to assume — reported, never guessed.', '');
    const items = [...skeleton.unresolved].sort((a, b) =>
      a.file === b.file ? (a.line ?? 0) - (b.line ?? 0) : a.file < b.file ? -1 : 1,
    );
    for (const u of items) out.push(`- ${code(`${u.file}${u.line ? `:${u.line}` : ''}`)} — ${u.reason}`);
    for (const note of model.notes) out.push(`- ${note}`);
    out.push('');
  }

  return out.join('\n');
}

/** Every file an infrastructure module is made of, for the registry's shared entry. */
export function infraFiles(s: SkeletonService): string[] {
  return [...new Set([s.source.file, ...s.controllers.map((c) => c.file), ...s.providers.map((p) => p.file), ...(s.files ?? [])])].sort();
}

const sortedIds = (ids: Iterable<string>): string[] => [...new Set(ids)].sort();

/**
 * "Serves 61 routes under /api, 7 under /auth, 2 at the root. " — which path groups a
 * server's routes fall in, so a reader sees that /auth or /internal sit outside the
 * prefix the clients use.
 */
function routeGroups(server: SkeletonServer): string {
  if (!server.routes.length) return '';
  const counts = new Map<string, number>();
  for (const r of server.routes) {
    const segments = r.path.split('/').filter(Boolean);
    const prefixed = server.globalPrefix && segments[0] === server.globalPrefix;
    const group = prefixed ? `/${server.globalPrefix}` : segments.length > 1 ? `/${segments[0]}` : 'the root';
    counts.set(group, (counts.get(group) ?? 0) + 1);
  }
  const parts = [...counts]
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .map(([group, n], i) => `${i === 0 ? plural(n, 'route') : n} ${group === 'the root' ? 'at the root' : `under ${code(group)}`}`);
  return `Serves ${parts.join(', ')}. `;
}

/** Shared files by directory, so a list of 80 paths reads as a handful of places. */
function sharedSummary(files: readonly string[]): string[] {
  const byDir = new Map<string, number>();
  for (const f of files) {
    const dir = f.includes('/') ? f.slice(0, f.lastIndexOf('/')) : '.';
    byDir.set(dir, (byDir.get(dir) ?? 0) + 1);
  }
  return [...byDir].sort((a, b) => (a[0] < b[0] ? -1 : 1)).map(([dir, n]) => `- ${code(`${dir}/`)} — ${plural(n, 'file')}`);
}
