import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  clientSignature,
  generateBoundaryClient,
  planBoundaryClient,
  tsType,
} from '../dist/project/boundary-client.js';
import type { ProjectSource } from '../dist/project/source.js';

/**
 * Boundary type-sync's value is faithful types (drift-prevention) in the project's own
 * idiom. These cover the three seams: JSON Schema -> TS is exact, the plan resolves the
 * boundary's exposed services to their io schemas, and the memo signature moves iff the
 * generated bytes would.
 */

// An in-memory project source — the subset planBoundaryClient reads.
function source(files: Record<string, string>): ProjectSource {
  const list = Object.keys(files).sort();
  return {
    exists: (p: string) => p in files,
    read: (p: string) => files[p],
    glob: (pattern: string) => list.filter((p) => p === pattern),
    list: () => list,
  } as ProjectSource;
}

const DOCUMENT_SCHEMA = JSON.stringify({
  type: 'object',
  required: ['id', 'body'],
  additionalProperties: false,
  properties: {
    id: { type: 'string', minLength: 1 },
    body: { type: 'string' },
    source: { type: 'string' },
    receivedAt: { type: 'string', format: 'date-time' },
  },
});

const RECORD_SCHEMA = JSON.stringify({
  type: 'object',
  required: ['id', 'category', 'confidence'],
  properties: {
    id: { type: 'string' },
    category: { type: 'string', enum: ['invoice', 'contract', 'correspondence', 'other'] },
    confidence: { type: 'number' },
    summary: { type: 'string' },
    enrichedFrom: { type: 'array', items: { type: 'string' } },
  },
});

function docPipeline(overrides: Record<string, string> = {}): Record<string, string> {
  return {
    'civil/civil.yaml': `apiVersion: civil/v1
kind: Project
metadata: { id: doc-pipeline, name: Document Pipeline }
spec:
  composition: civil/app.yaml
  language: python
`,
    'civil/app.yaml': `apiVersion: civil/v1
kind: Composition
metadata: { id: doc-pipeline, name: Document Pipeline }
spec:
  nodes:
    - { id: web, type: client, client: web, path: web, dev: "npm run dev" }
    - { id: public-api, type: boundary, boundary: api, exposes: [classify, save-record] }
    - { id: agent-tools, type: boundary, boundary: mcp, exposes: [classify] }
    - { id: classify, type: service, impl: { graph: civil/graphs/classify.graph.yaml } }
    - { id: save-record, type: service, impl: { entrypoint: src/services/save_record.py } }
`,
    'civil/graphs/classify.graph.yaml': `apiVersion: civil/v1
kind: Graph
metadata: { id: classify, name: Classify }
spec:
  nodes:
    - { id: document, type: io, direction: in, schema: schemas/document.schema.json }
    - { id: record, type: io, direction: out, schema: schemas/record.schema.json }
    - { id: thinking, type: io, direction: out, kind: progress }
`,
    'schemas/document.schema.json': DOCUMENT_SCHEMA,
    'schemas/record.schema.json': RECORD_SCHEMA,
    'web/src/main.ts': '// hand-written client entry\n',
    ...overrides,
  };
}

test('tsType renders objects, optionals, enums, and arrays faithfully', () => {
  assert.equal(
    tsType(JSON.parse(DOCUMENT_SCHEMA)),
    `{\n  id: string;\n  body: string;\n  source?: string;\n  receivedAt?: string;\n}`,
  );
  const record = tsType(JSON.parse(RECORD_SCHEMA));
  assert.match(record, /category: 'invoice' \| 'contract' \| 'correspondence' \| 'other';/);
  assert.match(record, /confidence: number;/);
  assert.match(record, /enrichedFrom\?: string\[\];/);
});

test('tsType degrades unknown shapes to unknown, never a guess', () => {
  assert.equal(tsType({ oneOf: [{ type: 'string' }, { type: 'number' }] }), 'unknown');
  assert.equal(tsType(true), 'unknown');
});

test('planBoundaryClient resolves graph-backed and function-backed endpoints', async () => {
  const plan = await planBoundaryClient(source(docPipeline()));
  assert.ok(plan, 'a web client + api boundary yields a plan');
  assert.equal(plan!.clientPath, 'web/src/civil/client.ts');

  // exposes order, mcp boundary ignored, node id -> fn/typeBase.
  assert.deepEqual(
    plan!.endpoints.map((e) => [e.name, e.fn, e.typeBase]),
    [
      ['classify', 'classify', 'Classify'],
      ['save-record', 'saveRecord', 'SaveRecord'],
    ],
  );

  const classify = plan!.endpoints[0]!;
  assert.deepEqual(classify.inputSchema, JSON.parse(DOCUMENT_SCHEMA), 'io in schema resolved');
  assert.deepEqual(classify.outputSchema, JSON.parse(RECORD_SCHEMA), 'io out schema resolved');

  const save = plan!.endpoints[1]!;
  assert.equal(save.inputSchema, null, 'a function-backed service declares no schema here');
  assert.equal(save.outputSchema, null);
});

test('generateBoundaryClient emits typed wrappers and role boundary-client', async () => {
  const plan = await planBoundaryClient(source(docPipeline()));
  const { files, roles } = generateBoundaryClient(plan!);
  const code = files['web/src/civil/client.ts']!;
  assert.equal(roles['web/src/civil/client.ts'], 'boundary-client');

  assert.match(code, /export interface ClassifyInput \{/);
  assert.match(code, /export interface ClassifyOutput \{/);
  assert.match(code, /export type SaveRecordInput = unknown;/);
  assert.match(
    code,
    /export function classify\(input: ClassifyInput\): Promise<ClassifyOutput> \{/,
  );
  assert.match(code, /return post\("\/classify", input\);/);
  assert.match(code, /export function saveRecord\(input: SaveRecordInput\)/);
  assert.match(code, /return post\("\/save-record", input\);/);
});

test('the client signature tracks the schema — drift regenerates, unchanged replays', async () => {
  const base = await planBoundaryClient(source(docPipeline()));
  const same = await planBoundaryClient(source(docPipeline()));
  assert.equal(clientSignature(base!), clientSignature(same!), 'unchanged inputs, same signature');

  // A field added to the input schema must move the signature (the memo would miss).
  const drifted = await planBoundaryClient(
    source(
      docPipeline({
        'schemas/document.schema.json': JSON.stringify({
          type: 'object',
          required: ['id', 'body'],
          properties: {
            id: { type: 'string' },
            body: { type: 'string' },
            language: { type: 'string' }, // new field
          },
        }),
      }),
    ),
  );
  assert.notEqual(
    clientSignature(base!),
    clientSignature(drifted!),
    'a schema edit changes the signature',
  );
});

test('no web client, or no api boundary, yields no plan', async () => {
  const noWeb = docPipeline();
  delete noWeb['web/src/main.ts'];
  noWeb['civil/app.yaml'] = noWeb['civil/app.yaml']!.replace(
    '- { id: web, type: client, client: web, path: web, dev: "npm run dev" }\n    ',
    '',
  );
  assert.equal(await planBoundaryClient(source(noWeb)), null, 'no web client -> null');

  const noApi = docPipeline();
  noApi['civil/app.yaml'] = noApi['civil/app.yaml']!.replace('boundary: api', 'boundary: mcp');
  assert.equal(await planBoundaryClient(source(noApi)), null, 'no api boundary -> null');
});

test('a flat client (no src dir) lands the client beside its path', async () => {
  const flat = docPipeline();
  delete flat['web/src/main.ts'];
  flat['web/main.ts'] = '// flat client\n';
  const plan = await planBoundaryClient(source(flat));
  assert.equal(plan!.clientPath, 'web/civil/client.ts');
});
